name: Build & Deploy Portfolio

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.9"

      - name: Create .env
        run: |
          cat <<EOF > .env
          URL=${{ secrets.URL }}
          PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}
          USER_NAME=${{ secrets.USER_NAME }}
          USER_PASS=${{ secrets.USER_PASS }}
          STORAGE_URL=${{ secrets.STORAGE_URL }}
          EOF

      - name: Get Packages
        run: flutter pub get

      - name: Build Web
        run:  flutter build web --release --base-href /

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: atikurzamanpallob/atikurzamanpallob.github.io
          publish_branch: main
          publish_dir: build/web